### ISSUE TITLE
Rename `frontpage` to `landing`

### ISSUE THREAD

**Issue by henrijs** [wunderio/next-drupal-starterkit#173]
Big fan, excellent work!

Naming is one of the hardest problems in IT, so here I come with most urgentest and major breaking change proposal :) Can we do what's in title? I mean, most sites will use landing for front page and few will have separate content type for front page.

**Comment by vermario** [comment]
hi Henrijs! 

I don't think the term `landing page` is synonymous with "the starting page of a website" 

it seems to mean slightly different things, for example: 

(https://unbounce.com/landing-page-articles/what-is-a-landing-page/) 
> In digital marketing, a landing page is a standalone web page, created specifically for a marketing or advertising campaign. 

https://support.google.com/google-ads/answer/14086?hl=en
> Landing page: Definition: Landing page is the webpage where people end up after they click your ad. The URL of this page is usually the same as your ad's final URL.

https://mailchimp.com/marketing-glossary/landing-pages/
> A landing page is a standalone web page that potential customers can “land” on when they click through from an [email](https://mailchimp.com/solutions/email-marketing-platform/), [ad](https://mailchimp.com/marketing-glossary/display-ads/), or other digital location.


To me at least frontpage (or homepage?) is what we normally mean with "the page you get if you type the domain, or you click the logo" so that's we went with... 


What do you think?

**Comment by pulakka** [comment]
My two cents on the topic is that front page is quite rarely needed as its own content type. Landing page is a common naming convention for the starting pages of different sections and very often has the same layout as the site’s front page. 

From reusability perspective it would be better to have a content type that can be used on multiple occasions instead of having a content type for only one node. If a site needs a more customised front page then that could created, but I think the starting point for the template should be as flexible as possible.

**Comment by vermario** [comment]
hi @pulakka ! 

going for a separate content type for the frontpage in this context is due to the fact that (contrary to normal Drupal operations) there really isn't the concept of "homepage", so we are simulating it with:
* adding the index.ts file (that automatically is  associated with the / (and /fi, /sv ) url 
* inside that file, we [do a query and render the the content of the `frontpage` node for that language](https://github.com/wunderio/next-drupal-starterkit/blob/a2856f2f406e05500ac152d45b0fb495d0c44344/next/pages/index.tsx#L57)
* adding some code on[ the Drupal side to make sure that there is only one node for a language of that type](https://github.com/wunderio/next-drupal-starterkit/tree/main/drupal/web/modules/custom/wunder_next/src/Plugin/Validation/Constraint)
* we also add a[ redirect for the actual path of the frontpage to the "/" path for the language
](https://github.com/wunderio/next-drupal-starterkit/blob/a2856f2f406e05500ac152d45b0fb495d0c44344/next/pages/%5B...slug%5D.tsx#L142)

When we set this up, this sounded like the easiest approach for editors etc...

But we can switch to another approach if we find an easier one :) 

What could that be?
